### ISSUE TITLE
Robot stop on max current reached

### ISSUE THREAD

**Issue by MaximilienNaveau** [open-dynamic-robot-initiative/blmc_robots#28]
## Problem

We have an issue with the use of the Teststand and the Solo robots concerning the safety solution trigger upon max current reach.

The current behavior is that the robots shutdown.
While for the locomotion robots a better solution would be simply to saturate the current.
For the locomotion robot safety measures are also taken at a higher level in the implementation.

## Potential Solution

A solution that is suitable for all robots would be nice!
Maybe a solution where you activate/deactivate safety checks.
I mean like a bank of methods that could check joint limits, current/torque limits, etc.
And upon creation of the joint module you could select the safeties that you require for you robot.

WDYT?

## Short term solution

I will implement a saturation behavior in the Teststand and the Solo robots.

**Comment by sheim** [comment]
>  Maybe a solution where you activate/deactivate safety checks.

Would be nice if checks could be individually toggled between "off", "warning" and "error". As in, sometimes you'll want the robot to actually shut down. But sometimes, even if you don't want it to shut down, you still want to know (and log with a time-stamp) when a certain safety-check failed.

**Comment by MaximilienNaveau** [comment]
related pull request: https://github.com/open-dynamic-robot-initiative/blmc_robots/pull/29

**Comment by mwuethri** [comment]
I am not sure what is the right level to put these safety checks in place.
The idea now is that the safety checks are done inside RobotDriver, i.e.
one level higher than BlmcJointModules, because they may be quite
robot-specific and this also makes it easier to log which torque was
actually applied. So the check in BlmcJointModules should never be
triggered, it is just there in case something went really really wrong, as
a last resort.

Il giorno mar 12 nov 2019 alle ore 16:40 Naveau <notifications@github.com>
ha scritto:

**Comment by MaximilienNaveau** [comment]
Ok, so the approach I took in the pull request [above] was the correct answer?

**Comment by mwuethri** [comment]
yes, just saw that, this is exactly where i would suggest to do it.

in case you want to have a look, we do our safety checks here
<https://github.com/open-dynamic-robot-initiative/blmc_robots/blob/master/include/blmc_robots/n_joint_blmc_robot_driver.hpp#L247>.
note that we keep track of both the desired and the applied action here
<https://github.com/open-dynamic-robot-initiative/robot_interfaces/blob/master/include/robot_interfaces/robot_backend.hpp#L174>,
in a class which is robot-independent. in case you would like to use these
classes, all you need to do is have your robot class derive from the
RobotDriver
<https://github.com/open-dynamic-robot-initiative/robot_interfaces/blob/master/include/robot_interfaces/robot_driver.hpp>
class.

Il giorno mar 12 nov 2019 alle ore 17:04 Naveau <notifications@github.com>
ha scritto:
